id         = "taktojakuba/tui-wg"
name       = "tui-wg"
version    = "0.4.9"
plugin_api = 3
author     = "taktojakuba"

[[widget]]
id    = "volume"
entry = "volume.luau"
[[widget]]
id    = "powerprofile"
entry = "powerprofile.luau"
[[widget]]
id    = "battery"
entry = "battery.luau"
[[widget]]
id    = "wifi"
entry = "wifi.luau"

  [[widget.setting]]
  key       = "wifi_interface"
  type      = "string"
  label_key = "settings.wifi_interface.label"
  default   = "wlan0"

[[widget]]
id    = "cpu"
entry = "cpu.luau"
[[widget]]
id    = "ram"
entry = "ram.luau"

[[widget]]
id = "weather"
entry = "weather.luau"

  [[widget.setting]]
  key       = "location"
  type      = "string"
  label_key = "settings.location.label"
  default   = "Warsaw"

[[widget]]
id    = "visualizer"
entry = "visualizer.luau"

  [[widget.setting]]
  key       = "width"
  type      = "int"
  label_key = "settings.width.label"
  default   = 30
  min       = 10
  max       = 500

  [[widget.setting]]
  key       = "sensitivity"
  type      = "float"
  label_key = "settings.sensitivity.label"
  default   = 1.5
  min       = 0.1
  max       = 10.0

[[widget]]
id    = "separator"
entry = "separator.luau"

[[widget]]
id    = "slash-separator"
entry = "slash-separator.luau"

[[widget]]
id    = "brackets"
entry = "brackets.luau"

  [[widget.setting]]
  key       = "side"
  type      = "select"
  label_key = "settings.side.label"
  default   = "left"
  options   = [
    { value = "left",  label_key = "settings.side.left" },
    { value = "right", label_key = "settings.side.right" },
  ]
