id         = "taktojakuba/tui-wg"
name       = "tui-wg"
version    = "0.4.7"
plugin_api = 3
author     = "taktojakuba"

[[widget]]
id    = "volume"
entry = "volume.luau"
[[widget]]
id    = "powerprofile"
entry = "powerprofile.luau"
[[widget]]
id    = "battery"
entry = "battery.luau"
[[widget]]
id    = "wifi"
entry = "wifi.luau"

  [[widget.setting]]
  key       = "wifi_interface"
  type      = "string"
  label_key = "settings.wifi_interface.label"
  default   = "wlan0"

[[widget]]
id    = "cpu"
entry = "cpu.luau"
[[widget]]
id    = "ram"
entry = "ram.luau"

[[widget]]
id = "weather"
entry = "weather.luau"

  [[widget.setting]]
  key       = "location"
  type      = "string"
  label_key = "settings.location.label"
  default   = "Warsaw"

[[widget]]
id    = "visualizer"
entry = "visualizer.luau"

  [[widget.setting]]
  key       = "width"
  type      = "int"
  label_key = "settings.width.label"
  default   = 30
  min       = 10
  max       = 500
